# Generated by Django 5.2.15 on 2026-06-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='highlight',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
