# Generated by Django 5.2.15 on 2026-06-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippet_highlight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='highlight',
            new_name='highlighted',
        ),
    ]
